import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Phantom",
  description: "Generated by create next app",
  icons: "/logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      {/* <Sidebar /> */}
      {children}
    </main>
  );
}
